apiVersion: v1
kind: Secret
metadata:
  name: terminal-api-secret
  namespace: terminal-shop-dev
type: Opaque
stringData:
  TERMINAL_BEARER_TOKEN: dHJtX3Rlc3RfOWQzYTQ5MWYyNTY5YjI4YTE0MGI=  # Replace with your actual token
