apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "terminal-operator.fullname" . }}-role
rules:
- apiGroups: ["coffee.terminal.sh"]
  resources: ["coffeeprofiles", "coffeeaddresses", "coffeecards", "coffeeorders", "coffeesubscriptions", "coffeecarts", "terminaltokens", "coffeeapps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "terminal-operator.fullname" . }}-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "terminal-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "terminal-operator.fullname" . }}-role