apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: coffeeprofiles.coffee.terminal.sh
spec:
  group: coffee.terminal.sh
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "User profile specification for the coffee ordering system."
              required:
                - email
                - name
              properties:
                email:
                  type: string
                  description: "User's email address for notifications."
                name:
                  type: string
                  description: "User's full name."
            status:
              type: object
              description: "Current status of the user profile."
              properties:
                phase:
                  type: string
                  description: "Current state of the profile. Possible values:\n- Pending: Initial state\n- Synced: Profile successfully synced with API\n- Failed: Profile sync failed"
                  enum:
                    - Pending
                    - Synced
                    - Failed
                message:
                  type: string
                  description: "Detailed status message or error info."
                observedGeneration:
                  type: integer
                  description: "The most recent generation observed by the controller."
                lastSyncTime:
                  type: string
                  format: "date-time"
                  description: "Timestamp of the last successful profile synchronization."
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Phase
          type: string
          description: Current phase of the profile
          jsonPath: .status.phase
        - name: Email
          type: string
          description: Email address
          jsonPath: .spec.email
        - name: Name
          type: string
          description: User name
          jsonPath: .spec.name
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: coffeeprofiles
    singular: coffeeprofile
    kind: CoffeeProfile
    shortNames:
      - cprofile
      - cp