apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: coffeeapps.coffee.terminal.sh
spec:
  group: coffee.terminal.sh
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "OAuth app specification for Terminal API."
              required:
                - name
                - redirectUri
              properties:
                name:
                  type: string
                  description: "Name of the OAuth app."
                redirectUri:
                  type: string
                  description: "Redirect URI for OAuth flow."
            status:
              type: object
              description: "Current status of the OAuth app."
              properties:
                phase:
                  type: string
                  description: "Current state of the app."
                  enum:
                    - Pending
                    - Active
                    - Failed
                appId:
                  type: string
                  description: "The Terminal API app ID."
                secretRef:
                  type: object
                  description: "Reference to the Kubernetes secret containing the app credentials."
                  properties:
                    name:
                      type: string
                      description: "Name of the secret."
                    namespace:
                      type: string
                      description: "Namespace of the secret."
                message:
                  type: string
                  description: "Detailed status message or error info."
                observedGeneration:
                  type: integer
                  description: "The most recent generation observed by the controller."
                lastStatusCheck:
                  type: string
                  format: date-time
                  description: "Timestamp of the last status check with the Terminal API."
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Phase
          type: string
          description: Current phase of the app
          jsonPath: .status.phase
        - name: AppID
          type: string
          description: Terminal API App ID
          jsonPath: .status.appId
        - name: Message
          type: string
          description: Status message
          jsonPath: .status.message
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: coffeeapps
    singular: coffeeapp
    kind: CoffeeApp
    shortNames:
      - capp
      - ca