apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: terminaltokens.coffee.terminal.sh
spec:
  group: coffee.terminal.sh
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "Terminal API personal access token specification."
              properties:
                description:
                  type: string
                  description: "Optional description of the token's purpose."
            status:
              type: object
              description: "Current status of the Terminal API token."
              properties:
                phase:
                  type: string
                  description: "Current state of the token."
                  enum:
                    - Pending
                    - Active
                    - Failed
                tokenId:
                  type: string
                  description: "The Terminal API token ID."
                created:
                  type: string
                  format: date-time
                  description: "Creation timestamp of the token."
                message:
                  type: string
                  description: "Detailed status message or error info."
                observedGeneration:
                  type: integer
                  description: "The most recent generation observed by the controller."
                lastStatusCheck:
                  type: string
                  format: date-time
                  description: "Timestamp of the last status check with the Terminal API."
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Phase
          type: string
          description: Current phase of the token
          jsonPath: .status.phase
        - name: TokenID
          type: string
          description: Terminal API Token ID
          jsonPath: .status.tokenId
        - name: Created
          type: string
          description: Creation timestamp
          jsonPath: .status.created
        - name: Message
          type: string
          description: Status message
          jsonPath: .status.message
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: terminaltokens
    singular: terminaltoken
    kind: TerminalToken
    shortNames:
      - ttoken
      - tt