apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: coffeeorders.coffee.terminal.sh
spec:
  group: coffee.terminal.sh
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "Specification for the desired coffee order."
              required:
                - productVariantId
                - address
                - email
              properties:
                productVariantId:
                  type: string
                  description: "The specific product variant ID to order (e.g., var_...)."
                quantity:
                  type: integer
                  description: "Number of items to order."
                  default: 1
                  minimum: 1
                email:
                  type: string
                  description: "Customer email address for order notifications."
                address:
                  type: object
                  description: "Shipping address details for this order."
                  required:
                    - name
                    - street1
                    - city
                    - zip
                    - country
                  properties:
                    name:
                      type: string
                      description: "Recipient name."
                    street1:
                      type: string
                      description: "Street address line 1."
                    street2:
                      type: string
                      description: "Street address line 2 (optional)."
                    city:
                      type: string
                    state:
                      type: string
                      description: "State or province (optional)."
                    zip:
                      type: string
                      description: "Postal code."
                    country:
                      type: string
                      description: "Two-letter country code (e.g., US)."
                cardToken:
                  type: string
                  description: "Stripe card token (e.g., tok_...) to use for payment."
            status:
              type: object
              description: "Current status of the coffee order process."
              properties:
                phase:
                  type: string
                  description: "Lifecycle phase (e.g., Pending, Processing, Ordered, Failed)."
                message:
                  type: string
                  description: "Detailed status message or error info."
                orderId:
                  type: string
                  description: "The Terminal API order ID once created."
                observedGeneration:
                  type: integer
                  description: "The most recent generation observed by the controller."
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: coffeeorders
    singular: coffeeorder
    kind: CoffeeOrder
    shortNames:
      - corder
      - co