apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: coffeeorders.coffee.terminal.sh
spec:
  group: coffee.terminal.sh
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "Specification for the desired coffee order."
              required:
                - productVariantId
                - profileRef
                - addressRef
                - cardRef
              properties:
                productVariantId:
                  type: string
                  description: "The specific product variant ID to order (e.g., var_...)."
                quantity:
                  type: integer
                  description: "Number of items to order."
                  default: 1
                  minimum: 1
                profileRef:
                  type: object
                  description: "Reference to a CoffeeProfile resource."
                  required:
                    - name
                  properties:
                    name:
                      type: string
                      description: "Name of the CoffeeProfile resource."
                    namespace:
                      type: string
                      description: "Namespace of the CoffeeProfile resource. Defaults to the same namespace as this resource if not specified."
                addressRef:
                  type: object
                  description: "Reference to a CoffeeAddress resource."
                  required:
                    - name
                  properties:
                    name:
                      type: string
                      description: "Name of the CoffeeAddress resource."
                    namespace:
                      type: string
                      description: "Namespace of the CoffeeAddress resource. Defaults to the same namespace as this resource if not specified."
                cardRef:
                  type: object
                  description: "Reference to a CoffeeCard resource."
                  required:
                    - name
                  properties:
                    name:
                      type: string
                      description: "Name of the CoffeeCard resource."
                    namespace:
                      type: string
                      description: "Namespace of the CoffeeCard resource. Defaults to the same namespace as this resource if not specified."
                priority:
                  type: string
                  description: "Order priority level. Premium incurs higher costs but faster processing."
                  enum:
                    - Standard
                    - Premium
                  default: "Standard"
                notes:
                  type: string
                  description: "Special instructions for the order (optional)."
                scheduling:
                  type: object
                  description: "Optional scheduling parameters for the order."
                  properties:
                    deliveryWindow:
                      type: string
                      description: "Preferred delivery window (morning/afternoon)."
                      enum: 
                        - morning
                        - afternoon
                      default: "morning"
            status:
              type: object
              description: "Current status of the coffee order process."
              properties:
                phase:
                  type: string
                  description: "Current state of the order. Possible values:\n- Pending: Initial state\n- Processing: Order is being created\n- Ordered: Order successfully placed\n- Shipped: Order has been shipped\n- Delivered: Order has been delivered\n- Cancelled: Order was cancelled\n- Failed: Order failed to process"
                  enum:
                    - Pending
                    - Processing
                    - Ordered
                    - Shipped
                    - Delivered
                    - Cancelled
                    - Failed
                message:
                  type: string
                  description: "Detailed status message or error info."
                orderId:
                  type: string
                  description: "The Terminal API order ID once created."
                profileReadyStatus:
                  type: boolean
                  description: "Indicates if the referenced profile is ready (true) or not (false)."
                addressReadyStatus:
                  type: boolean
                  description: "Indicates if the referenced address is ready (true) or not (false)."
                cardReadyStatus:
                  type: boolean
                  description: "Indicates if the referenced card is ready (true) or not (false)."
                observedGeneration:
                  type: integer
                  description: "The most recent generation observed by the controller."
                lastStatusCheck:
                  type: string
                  format: "date-time"
                  description: "Timestamp of the last status check with the Terminal API."
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Phase
          type: string
          description: Current phase of the order
          jsonPath: .status.phase
        - name: OrderID
          type: string
          description: Terminal API Order ID
          jsonPath: .status.orderId
        - name: Address
          type: string
          description: Address reference
          jsonPath: .spec.addressRef.name
        - name: Card
          type: string
          description: Payment card reference
          jsonPath: .spec.cardRef.name
        - name: Message
          type: string
          description: Status message
          jsonPath: .status.message
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: coffeeorders
    singular: coffeeorder
    kind: CoffeeOrder
    shortNames:
      - corder
      - co