apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: coffeeaddresses.coffee.terminal.sh
spec:
  group: coffee.terminal.sh
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "Address specification for coffee delivery."
              required:
                - name
                - street1
                - city
                - zip
                - country
              properties:
                name:
                  type: string
                  description: "Recipient name."
                street1:
                  type: string
                  description: "Street address line 1."
                street2:
                  type: string
                  description: "Street address line 2 (optional)."
                city:
                  type: string
                  description: "City name."
                state:
                  type: string
                  description: "State or province (optional, not used by Terminal API)."
                zip:
                  type: string
                  description: "Postal code."
                country:
                  type: string
                  description: "Two-letter country code (e.g., US)."
            status:
              type: object
              description: "Current status of the coffee address."
              properties:
                addressId:
                  type: string
                  description: "The Terminal API address ID once created."
                phase:
                  type: string
                  description: "Current state of the address. Possible values:\n- Pending: Initial state\n- Verified: Address has been verified\n- Failed: Address failed to verify"
                  enum:
                    - Pending
                    - Verified
                    - Failed
                message:
                  type: string
                  description: "Detailed status message or error info."
                observedGeneration:
                  type: integer
                  description: "The most recent generation observed by the controller."
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Phase
          type: string
          description: Current phase of the address
          jsonPath: .status.phase
        - name: AddressID
          type: string
          description: Terminal API Address ID
          jsonPath: .status.addressId
        - name: Message
          type: string
          description: Status message
          jsonPath: .status.message
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: coffeeaddresses
    singular: coffeeaddress
    kind: CoffeeAddress
    shortNames:
      - caddress
      - ca