image:
  repository: ghcr.io/joshyorko/terminal-operator-k8s
  tag: 0.2.0
  pullPolicy: Always

# ENVIRONMENT CONFIG
env:
  TERMINAL_ENVIRONMENT: "dev"  # USE "production" WHEN READY FOR REAL COFFEE!

# USE KUBE SECRET FOR TOKEN SECURITY!
existingSecret: "terminal-api-secret"  # NAME OF SECRET WITH TOKEN
secretTokenKey: "TERMINAL_BEARER_TOKEN"

resources: {}

serviceAccount:
  create: true
  name: ""